name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
      with:
        swift-version: "5.8.0"
    - name: Get Swift Version
      run: swift --version
    - name: Build
      run: swift build -v

  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: swift test -v