on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  destination: 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0'

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v

  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -s "/Applications/Xcode_14.0.1.app"
    - name: Test
      run: swift test -v