name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    DEVELOPER_DIR: /Applications/Xcode_14.1.app

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.8.0"
    - name: Get Swift Version
      run: swift --version
    - name: Build
      run: swift build -v

  test:
    runs-on: macOS-latest
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.8.0"
    - name: Get Swift Version
      run: swift --version
    - name: Test
      run: swift test -v